------------Need to find new and repeat customers from the customers table ------------
create table customer_orders (
order_id integer,
customer_id integer,
order_date date,
order_amount integer
);



insert into customer_orders values(1,100,cast('2022-01-01' as date),2000),(2,200,cast('2022-01-01' as date),2500),(3,300,cast('2022-01-01' as date),2100)
,(4,100,cast('2022-01-02' as date),2000),(5,400,cast('2022-01-02' as date),2200),(6,500,cast('2022-01-02' as date),2700)
,(7,100,cast('2022-01-03' as date),3000),(8,400,cast('2022-01-03' as date),1000),(9,600,cast('2022-01-03' as date),3000)
;

-- solution to find no of new customers and no of repeat customers
with first_visit as (select customer_id, min(order_date) as first_visit_date
from customer_orders
group by customer_id)
select co.order_date ,sum(case when first_visit_date = order_date then 1 else 0 end) as no_of_new_customers,
sum(case when first_visit_date != order_date then 1 else 0 end) as no_of_repeat_customers
from customer_orders co
join first_visit fv 
on co.customer_id = fv.customer_id
group by order_date


-- solution for revenue generated by new customers and revenue generated by repeat customers
with first_visit as (select customer_id, min(order_date) as first_visit_date
from customer_orders
group by customer_id)
select co.order_date ,sum(case when first_visit_date = order_date then order_amount else 0 end) as no_of_new_customers_revenue,
sum(case when first_visit_date != order_date then order_amount else 0 end) as no_of_repeat_customers_revenue
from customer_orders co
join first_visit fv 
on co.customer_id = fv.customer_id
group by order_date

